bugfix: missing field in record in pt-client dns request broke output and some strings were joined with | intended for list:
Traceback (most recent call last):
  File "/usr/local/bin/pt-client", line 9, in <module>
    load_entry_point('passivetotal==1.0.20', 'console_scripts', 'pt-client')()
  File "/home///pt_python_api/passivetotal/cli/client.py", line 315, in main
    output = write_output(data, args)
  File "/home///pt_python_api/passivetotal/cli/client.py", line 170, in write_output
    data = [getattr(data, arguments.format)]
  File "/home///pt_python_api/passivetotal/libs/dns.py", line 261, in table
    ordered[4] = "|".join(ordered[4])
IndexError: list index out of range

Fixed bug and issue with strange output